name = "icalendar-filter"
main = "./src/index.ts"
workers_dev = false
compatibility_date = "2022-10-19"

router = { pattern = "icalendar-filter.oziol.fr", custom_domain = true }

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
